### ISSUE TITLE
Japanese trains encoding problems

### ISSUE THREAD

**Issue by chatelao** [giggls/openptmap#1]
It seams like Japanese characters are not rendered / boxes only.

Looks like an encoding problem. Didn't check russia yet. There may bei similar problems.

**Comment by chatelao** [comment]
Russia / Israel without troubles.

Thailand / Korea / Japan strange.

=> This may be a font problem too?

**Comment by giggls** [comment]
Certainly is! Replaced fonts in style with Noto fontset as used in OSM Carto. Looks fine now.

However I just maintain a fork and not the upstream server thus this fix will not automatically appear on http://openptmap.org

![test-jp](https://user-images.githubusercontent.com/7996314/38241356-43c51606-3732-11e8-9381-65be35e74cd5.png)
