### ISSUE TITLE
Streaming Openptmap Tiles over HTTPS / SSL

### ISSUE THREAD

**Issue by Raruto** [giggls/openptmap#2]
Hi Sven, 
can I ask you if in the future you intend to add support to the HTTPS protocol on this site http://openptmap.org/

**Comment by giggls** [comment]
Hm, did you have a look at  README.md before opening this issue?

If so, is there something incomprehensible about this sentence:
"Fork and cleanup from http://openptmap.org/f/"

Will I need to make it even more clear that I am not in charge of http://openptmap.org/?

**Comment by Raruto** [comment]
First of all, thank you for your quick reply.
Regarding your sentence, I can tell you that I think the _verb tense_ is wrong:

ie, this: __"Fork and cleanup from http://openptmap.org/f/"__
should be: __"Fork*ed* and clean*ed* up from http://openptmap.org/f/"__

Tell me if I'm wrong, because I'm not native English speaker ..

Secondly, what confused me me mostly is that the following link: **http://openptmap.org/** is much more prominent than the one you "mentioned before" (along with the fact that there is not much else that would imply otherwise...)

> #  OSM Open Public Transport Map
> ## http://openptmap.org/
>
> ## Fork and cleanup from http://openptmap.org/f/
>
> The provided views are working with the database layout used in
> German Mapnik style
> (https://github.com/giggls/openstreetmap-carto-de)
>
> Original documentation is available in OSM Wiki
> http://wiki.openstreetmap.org/wiki/Openptmap

Anyway, thanks again for your time!

**Comment by giggls** [comment]
OK, I tried to clarify the README. I just forked the style for personal use and cleaned up the mess a bit.
http://openptmap.org/ is run by Markus Weber (AFAIK not on GitHub), the original author of the style.
